django/16-django-basics/learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),
    url(r'^index/$', views.index, name='index')
]

django/16-django-basics/learning_templates/learning_templates/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls'))
]

django/16-django-basics/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context_dict = {'text': 'hello man', 'number': 10}
    return render(request, 'basic_app/index.html', context_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

django/16-django-basics/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>HOME</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="nav-link" href="{% url 'basic_app:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend -->
      {% endblock %}
    </div>
  </body>
</html>

django/16-django-basics/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to index</h1>
<!--    <h2>{{ text|upper }}</h2>-->
    <h2>{{ text|cut:"man" }}</h2>
    <h3>{{ number|add:"99" }}</h3>
  {% endblock %}

django/16-django-basics/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to other</h1>
  {% endblock %}

django/16-django-basics/learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>HOME</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <h1>Welcome to relative</h1>
    <a href="{% url 'basic_app:other' %}">Other page</a>
    <a href="{% url 'admin:index' %}">Admin page</a>
    <a href="{% url 'basic_app:index' %}">Index page</a>
  </body>
</html>